# Generated by Django 4.2.30 on 2026-07-10 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_mesada_ultima_recarga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orcamentos', to='core.categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacoes', to='core.categoria', verbose_name='categoria'),
        ),
        migrations.AlterField(
            model_name='transacao',
            name='conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transacoes', to='core.conta', verbose_name='conta'),
        ),
    ]
